Request to api
fe-may23-BugBusters/product_catalog pull request #36
Opened 2023-11-07 15:21 UTC by SviatoslavVasyletskyi

## Task

[UI]: Send request to the API every time user change Sort and perPage select values

## Opis

- [ ] wysyła zapytanie do API za każdym razem, gdy użytkownik zmienia wartości sortowania lub ilości produktów na stronie 

## Zrzuty ekranu (opcjonalnie)

2023-11-07 17:13 UTC, cardinal1991 approved these changes

2023-11-08 10:00 UTC, Sancz0pansa commented
Sortowanie odbywa się po stronie serwera, nie jesteś w stanie z frontu sortować produktów właściwie jeśli nie pobierasz ich wszystkich na raz

2023-11-08 10:01 UTC, Sancz0pansa requested changes

2023-11-08 10:01 UTC, Sancz0pansa commented on src/components/PhonesPage/PhonesPage.tsx
> +  const sortedProducts = sortProducts();
jak wyżej

2023-11-08 14:28 UTC, ogospadzipalina approved these changes

2023-11-08 16:49 UTC, Sancz0pansa approved these changes

2023-11-09 08:05 UTC, merged